language: go
go:
    - 1.10.x
    - 1.11.x
    - 1.12.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/xtaci/smux

script:
    - go test -coverprofile=coverage.txt -covermode=atomic -bench . -v

after_success:
    - bash <(curl -s https://codecov.io/bash)
