package smux



































































































































































}	// Server: Accepted stream with baseID=103	// Server: Accepted stream with baseID=102	// Server: Accepted stream with baseID=101	// Client: Created stream with baseID=103	// Client: Created stream with baseID=102	// Client: Created stream with baseID=101	// Output:	}		stream.Close()		fmt.Printf("Client: Created stream with baseID=%d\n", baseID)		stream, _ := session.OpenStreamWithBaseID(baseID)		baseID := uint32(100 + i)	for i := 1; i <= 3; i++ {	// Create multiple streams with different base IDs	defer session.Close()	session, _ := Client(conn, nil)	defer conn.Close()	conn, _ := net.Dial("tcp", ln.Addr().String())	// Client side	}()		}			stream.Close()			fmt.Printf("Server: Accepted stream with baseID=%d\n", baseID)			baseID := stream.BaseID()			stream, _ := session.AcceptStream()		for i := 0; i < 3; i++ {		// Accept multiple streams and print their base IDs		defer session.Close()		session, _ := Server(conn, nil)		defer conn.Close()		conn, _ := ln.Accept()	go func() {	// Server goroutine	defer ln.Close()	ln, _ := net.Listen("tcp", "127.0.0.1:0")	// Setup: Create a TCP listenerfunc Example_MultipleBaseIDs() {// Example_MultipleBaseIDs demonstrates using multiple streams with different base IDs}	// Client: Received response: ok	// Server: Stream baseID=0	// Client: Stream baseID=0	// Output:	fmt.Printf("Client: Received response: %s\n", string(buf))	io.ReadFull(stream, buf)	buf := make([]byte, 2)	stream.Write([]byte("hello"))	fmt.Printf("Client: Stream baseID=%d\n", stream.BaseID())	defer stream.Close()	stream, _ := session.OpenStream()	// Traditional OpenStream without base ID	defer session.Close()	session, _ := Client(conn, nil)	defer conn.Close()	conn, _ := net.Dial("tcp", ln.Addr().String())	// Client side	}()		stream.Write([]byte("ok"))		io.ReadFull(stream, buf)		buf := make([]byte, 5)		fmt.Printf("Server: Stream baseID=%d\n", stream.BaseID())		// No base ID is set (default behavior)		defer stream.Close()		stream, _ := session.AcceptStream()		defer session.Close()		session, _ := Server(conn, nil)		defer conn.Close()		conn, _ := ln.Accept()	go func() {	// Server goroutine	defer ln.Close()	ln, _ := net.Listen("tcp", "127.0.0.1:0")	// Setup: Create a TCP listenerfunc Example_BackwardCompatibility() {// still works as before// Example_BackwardCompatibility demonstrates that traditional OpenStream}	// Client: Received response: pong	// Server: Received stream with baseID=42	// Client: Stream baseID=42	// Output:	fmt.Printf("Client: Received response: %s\n", string(buf))	io.ReadFull(stream, buf)	buf := make([]byte, 4)	// Receive response	stream.Write([]byte("ping"))	// Send data	fmt.Printf("Client: Stream baseID=%d\n", stream.BaseID())	// Verify base ID is set	defer stream.Close()	stream, _ := session.OpenStreamWithBaseID(baseID)	baseID := uint32(42)	// Create stream with a custom base ID	defer session.Close()	session, _ := Client(conn, nil)	defer conn.Close()	conn, _ := net.Dial("tcp", ln.Addr().String())	// Client side	}()		stream.Write([]byte("pong"))		io.ReadFull(stream, buf)		buf := make([]byte, 5)		// Echo back the received data		fmt.Printf("Server: Received stream with baseID=%d\n", baseID)		baseID := stream.BaseID()		// Retrieve the base ID sent by client		defer stream.Close()		stream, _ := session.AcceptStream()		// Accept incoming stream		defer session.Close()		session, _ := Server(conn, nil)		defer conn.Close()		conn, _ := ln.Accept()	go func() {	// Server goroutine	defer ln.Close()	ln, _ := net.Listen("tcp", "127.0.0.1:0")	// Setup: Create a TCP listenerfunc Example_OpenStreamWithBaseID() {// receiving side.// to create a stream with a specific base ID that can be retrieved on the// Example_OpenStreamWithBaseID demonstrates how to use OpenStreamWithBaseID)	"net"	"io"	"fmt"import (package smux